# Copyright (c) OpenBao
# SPDX-License-Identifier: MPL-2.0

## DOCKERHUB DOCKERFILE ##
FROM ubuntu:noble AS default

ARG BIN_NAME
ARG PRODUCT_VERSION
ARG PRODUCT_REVISION
ARG TARGETOS TARGETARCH

LABEL name="Vault" \
      maintainer="OpenBao Team <info@openbao.org>" \
      vendor="OpenBao" \
      version=${PRODUCT_VERSION} \
      release=${PRODUCT_REVISION} \
      revision=${PRODUCT_REVISION} \
      org.opencontainers.image.source="https://github.com/openbao/openbao" \
      summary="OpenBao is a tool for securely accessing secrets." \
      description="OpenBao is a tool for securely accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, and more. OpenBao provides a unified interface to any secret, while providing tight access control and recording a detailed audit log."

ENV NAME=$BIN_NAME
ENV VERSION=$PRODUCT_VERSION

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends curl dumb-init wget tzdata libcap2-bin ca-certificates jq; \
    if [ -z "$PRODUCT_VERSION" ]; then \
      PRODUCT_VERSION=$(curl -s https://api.github.com/repos/openbao/openbao/releases/latest | jq -r '.tag_name' | sed 's/^v//'); \
    fi; \
    wget https://github.com/openbao/openbao/releases/download/v${PRODUCT_VERSION}/openbao_${PRODUCT_VERSION}_linux_${TARGETARCH}.zip; \
    unzip openbao_${PRODUCT_VERSION}_linux_${TARGETARCH}.zip; \
    mv openbao /usr/bin/${BIN_NAME}; \
    chmod +x /usr/bin/${BIN_NAME}; \
    setcap cap_ipc_lock=ep /usr/bin/${BIN_NAME}; \
    rm openbao_${PRODUCT_VERSION}_linux_${TARGETARCH}.zip; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install latest su-exec
RUN  set -ex; \
     \
     curl -o /usr/local/bin/su-exec.c https://raw.githubusercontent.com/ncopa/su-exec/master/su-exec.c; \
     \
     fetch_deps='gcc libc-dev'; \
     apt-get update; \
     apt-get install -y --no-install-recommends $fetch_deps; \
     gcc -Wall \
         /usr/local/bin/su-exec.c -o/usr/local/bin/su-exec; \
     chown root:root /usr/local/bin/su-exec; \
     chmod 0755 /usr/local/bin/su-exec; \
     rm /usr/local/bin/su-exec.c; \
     \
     apt-get purge -y --auto-remove $fetch_deps
    
RUN groupadd ${NAME} && useradd -r -g ${NAME} ${NAME}

RUN mkdir -p /vault/logs && \
    mkdir -p /vault/file && \
    mkdir -p /vault/config && \
    chown -R ${NAME}:${NAME} /vault

VOLUME /vault/logs
VOLUME /vault/file

EXPOSE 8200

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    sed -i "s/openbao/${BIN_NAME}/g" /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

CMD ["server", "-dev"]
