FROM docker.io/ubuntu:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and Ansible
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3.12-venv \
    openssh-client \
    sshpass \
    git \
    ca-certificates \
    curl \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Ansible
RUN python3 -m venv /home/ansible/.venv && \
    . /home/ansible/.venv/bin/activate && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir --upgrade setuptools wheel && \
    python3 -m pip install --no-cache-dir ansible

# Create a directory for Ansible data
WORKDIR /ansible

# Create ansible user and configure sudo
RUN useradd -m ansible && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible && \
    chmod 0440 /etc/sudoers.d/ansible

# Set environment variables
ENV ANSIBLE_HOST_KEY_CHECKING=False
ENV ANSIBLE_REMOTE_TMP=/tmp/.ansible-remote
ENV ANSIBLE_BECOME_METHOD=sudo
ENV ANSIBLE_EXECUTABLE=/bin/bash
ENV PATH="/home/ansible/.venv/bin:$PATH"

RUN mkdir -p /home/ansible/.ansible/tmp && \
    chmod -R 755 /home/ansible/.ansible && \
    chown -R ansible:ansible /home/ansible/.ansible

# Switch to non-root user
USER ansible

# Verify all Ansible commands are available
RUN . /home/ansible/.venv/bin/activate && \
    ansible --version && \
    ansible-config --version && \
    ansible-console --version && \
    ansible-doc --version && \
    ansible-galaxy --version && \
    ansible-inventory --version && \
    ansible-playbook --version && \
    ansible-pull --version && \
    ansible-vault --version

# Set entrypoint script
ENTRYPOINT ["sh", "-c", ". /home/ansible/.venv/bin/activate && exec \"$@\"", "--"]
